export const ROUTES = {
  home: "/",
  welcome: "/welcome",
  newProject: "/new",
  project: (id: string) => `/p/${id}`,
  overview: (id: string) => `/p/${id}/overview`,
  write: (id: string, chapterId?: string) => (chapterId ? `/p/${id}/write/${chapterId}` : `/p/${id}/write`),
  outline: (id: string) => `/p/${id}/outline`,
  characters: (id: string) => `/p/${id}/characters`,
  character: (id: string, characterId: string) => `/p/${id}/characters/${characterId}`,
  world: (id: string) => `/p/${id}/world`,
  threads: (id: string) => `/p/${id}/threads`,
  timeline: (id: string) => `/p/${id}/timeline`,
  graph: (id: string) => `/p/${id}/graph`,
  insights: (id: string) => `/p/${id}/insights`,
  consistency: (id: string) => `/p/${id}/consistency`,
  ai: (id: string) => `/p/${id}/ai`,
  genesis: (id: string) => `/p/${id}/genesis`,
  usage: (id: string) => `/p/${id}/usage`,
  data: (id: string) => `/p/${id}/data`,
  settings: "/settings",
} as const;
